// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2J2zwIwlZEH3I49u5z6SCpFgJf8z96E',
    appId: '1:776828165461:web:a3c9178f07f3c1a91fe3dc',
    messagingSenderId: '776828165461',
    projectId: 'travelmate-polimi',
    authDomain: 'travelmate-polimi.firebaseapp.com',
    storageBucket: 'travelmate-polimi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWl4B0w93z5HZ5GPoC_2Vqp2q71hQ9OKM',
    appId: '1:776828165461:android:135c78dd853c61171fe3dc',
    messagingSenderId: '776828165461',
    projectId: 'travelmate-polimi',
    storageBucket: 'travelmate-polimi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmLl9s5TG_-Ki0cpWIIadOOa01X_KXb3U',
    appId: '1:776828165461:ios:a6f1a116fadf532b1fe3dc',
    messagingSenderId: '776828165461',
    projectId: 'travelmate-polimi',
    storageBucket: 'travelmate-polimi.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmLl9s5TG_-Ki0cpWIIadOOa01X_KXb3U',
    appId: '1:776828165461:ios:a6f1a116fadf532b1fe3dc',
    messagingSenderId: '776828165461',
    projectId: 'travelmate-polimi',
    storageBucket: 'travelmate-polimi.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT2J2zwIwlZEH3I49u5z6SCpFgJf8z96E',
    appId: '1:776828165461:web:a1d1a73a577610881fe3dc',
    messagingSenderId: '776828165461',
    projectId: 'travelmate-polimi',
    authDomain: 'travelmate-polimi.firebaseapp.com',
    storageBucket: 'travelmate-polimi.firebasestorage.app',
  );
}
