// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpRh1F9WspNIR7Sr2hqNmVVdGRr2CuQyk',
    appId: '1:851301611493:web:2829330699655850b6210c',
    messagingSenderId: '851301611493',
    projectId: 'travel-project-7bac6',
    authDomain: 'travel-project-7bac6.firebaseapp.com',
    storageBucket: 'travel-project-7bac6.firebasestorage.app',
    measurementId: 'G-62GWRPEX48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6RC4qtLp5cGHWzIweSPO7k4uJ0nwJMC4',
    appId: '1:851301611493:android:4d4ab8bd2f837ac8b6210c',
    messagingSenderId: '851301611493',
    projectId: 'travel-project-7bac6',
    storageBucket: 'travel-project-7bac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU95JJjGj1KWwFgGqt1LgmYMrUlLLttIU',
    appId: '1:851301611493:ios:8fa0e1da1233b9eab6210c',
    messagingSenderId: '851301611493',
    projectId: 'travel-project-7bac6',
    storageBucket: 'travel-project-7bac6.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU95JJjGj1KWwFgGqt1LgmYMrUlLLttIU',
    appId: '1:851301611493:ios:8fa0e1da1233b9eab6210c',
    messagingSenderId: '851301611493',
    projectId: 'travel-project-7bac6',
    storageBucket: 'travel-project-7bac6.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpRh1F9WspNIR7Sr2hqNmVVdGRr2CuQyk',
    appId: '1:851301611493:web:09b92ac6776b31abb6210c',
    messagingSenderId: '851301611493',
    projectId: 'travel-project-7bac6',
    authDomain: 'travel-project-7bac6.firebaseapp.com',
    storageBucket: 'travel-project-7bac6.firebasestorage.app',
    measurementId: 'G-GN1VDQFJD5',
  );
}
